baseurl = "http://inkdesign.jp/"
languageCode = "jp-ja"
title = "inkdesign"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
author = "hiloki"

[indexes]
  category = "categories"
  tag = "tags"
[Params]
  AuthorName = "Hiroki Tani"
  github = "hiloki/inkdesign"
  twitter = "hiloki"
  email = "contact@inkdesign"
  description = "I think design everywhere."
