baseurl: "http://inkdesign.jp/"
languageCode: "jp-ja"
title: "inkdesign"
name: "Hiroki Tani"
contentdir: "content"
publishdir: "public"
builddrafts: false
canonifyurls: true
metaDataFormat: "yaml"

indexes:
  category: "categories"
  tag: "tags"
params:
  AuthorName: "Hiroki Tani"
  github: "hiloki/inkdesign"
  twitter: "hiloki"
  email: "contact@inkdesign"
  description: "I think design everywhere."
